# This is a basic workflow to help you get started with Actions

name: workflow3
# Controls when the action will run. 
on:
  pull_request:
  push:
    branches: [ develop ]
  schedule:
    - cron:  '00 00 * * *'
  release:
    types: [published]
    
  workflow_dispatch:
  
jobs:
  nightly:
    runs-on: windows-latest
    steps:
    - name: Get release tag
      id: tag_name
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      
    - name: Check out the repo
      uses: actions/checkout@v2
      
   # - name: Npm Install
     # run: npm ci
      
    #- name: Npm Build
     # run: npm run build
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build image
      env:
        SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
      run: ./docker-image/build.sh
      
    - name: Build native with Maven
      run: mvn -B package
