# This is a basic workflow to help you get started with Actions

name: workflow3
# Controls when the action will run. 
on:
  pull_request:
  push:
    branches: [ develop ]
  schedule:
    - cron:  '00 00 * * *'
  release:
    types: [published]
    
  workflow_dispatch:
  
jobs:
  build:
    name: Build Java application
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build native with Maven
      run: mvn -B package
    - name: Upload jar for next job
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target
        retention-days: 1
        
  publish_in_dockerhub:
    name: Publish in DockerHub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Download jar from previous job
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Generate tag
        run: echo ::set-output name=tag::$(date +%s)
        id: project
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" 
      - name: Build image
        run: docker build --build-arg some_arg='${{ steps.project.outputs.tag }}' .
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/items:${{ steps.project.outputs.tag }}

