name: workflow5
on:
  push:
    branches: [ production ]
  workflow_dispatch:
  
jobs:
  build:
    name: Build Java application
    runs-on: windows-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build native with Maven
      run: mvn -B package
    - name: Upload jar for next job
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target
        retention-days: 1
        
  publish_in_heroku_registry:
      name: Docker
      runs-on: windows-latest
  deploy_to_heroku:
      name: Heroku
      runs-on: windows-latest
      

      
      
      
