# This is a basic workflow to help you get started with Actions

name: workflow1

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # antes de integrar
  push:
    branches: [ develop ]
  # antes de acabar
  pull_request:
    branches: [ feature/* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target
        retention-days: 1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    #rest
    - name: Build native with Maven
      run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test
    #unitary
    - name: Build native with Maven
      run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test
      

