name: workflow4
on:
  push:
    branches:
      -'release/**'
  pull_request:
    branches:
      -master
      
  workflow_dispatch:
  
jobs:

  job1:
    # Steps represent a sequence of tasks that will be executed as part of the job
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target
          retention-days: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      #rest
      - name: Build native with Maven
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test
      #unitary
      - name: Build native with Maven
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test

