# This is a basic workflow to help you get started with Actions

name: workflow2
# Controls when the action will run. 
on:
  # antes de acabar
  pull_request:
    branches: [ develop ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          name: target
          path: target/*.jar
          retention-days: 1
          ref: 'commit'
      - run: 
          mvn -B package

