# This is a basic workflow to help you get started with Actions

name: workflow3
# Controls when the action will run. 
on:
  pull_request:
  push:
    branches: [ develop ]
  schedule:
    - cron:  '00 00 * * *'
  release:
    types: [published]
    
  workflow_dispatch:
  
jobs:
  nightly:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target/*.jar
        retention-days: 1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
          privileged: true
          push: true
          tags: my-docker-hub-namespace/my-docker-hub-repository:latest
    - name: Build native with Maven
      run: mvn -B package
